/// Flutter icons My_home_logo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My_home_logo
///      fonts:
///       - asset: fonts/My_home_logo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class My_home_logo {
  My_home_logo._();

  static const _kFontFam = 'My_home_logo';
  static const String? _kFontPkg = null;

  static const IconData my_home_logo_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
