/// Flutter icons My_home_icon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My_home_icon
///      fonts:
///       - asset: fonts/My_home_icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class My_home_icon {
  My_home_icon._();

  static const _kFontFam = 'My_home_icon';
  static const String? _kFontPkg = null;

  static const IconData home_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_lines_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camaras_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
