/// Flutter icons Registration_icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Registration_icons
///      fonts:
///       - asset: fonts/Registration_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Registration_icons {
  Registration_icons._();

  static const _kFontFam = 'Registration_icons';
  static const String? _kFontPkg = null;

  static const IconData reg_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reg_email = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reg_phone = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reg_key_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
